cicd: Update config cicd

diff --git a/.github/workflows/Build and Push Docker Image.yml b/.github/workflows/Build and Push Docker Image.yml
--- a/.github/workflows/Build and Push Docker Image.yml
+++ b/.github/workflows/Build and Push Docker Image.yml
@@ -13,14 +13,19 @@ jobs:
 
         - name: Login to Docker Hub
           uses: docker/login-action@v2
-          with:
-            username: ${{ secrets.DOCKER_USERNAME }}
-            password: ${{ secrets.DOCKER_TOKEN }}
+          env:
+            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+            DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
 
         - name: Build and Push docker image
           run: |
-            docker build --platform linux --tag ${{ secrets.DOCKER_IMAGE_NAME }} .
-            docker push ${{ secrets.DOCKER_IMAGE_NAME }}  
+            IMAGE_TAG=${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
+            docker build --platform linux --tag $IMAGE_TAG .
+            docker push $IMAGE_TAG
+
+        - name: Update Docker Compose
+          run: |
+            sed -i "s|${{ secrets.DOCKER_IMAGE_NAME }}|${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}|g" docker-compose.yml
 
         - name: Log in to Azure
           uses: azure/login@v1
@@ -39,3 +44,11 @@ jobs:
           run: |
             az webapp stop --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
             az webapp start --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
+        
+        - name: Validate Deployment
+          run: |
+            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.URL_APP }})
+            if [ $RESPONSE -ne 200 ]; then
+              echo "Deployment failed with HTTP status $RESPONSE"
+              exit 1
+            fi
